### ISSUE TITLE
请求2.0版本的docker更新

### ISSUE THREAD

**Issue by skyshenma** [Haoshenqi0123/holiday#11]
大佬，你好，我用此api用来做了ios的中午午休时间自动开启专注模式，发现很好使。非常完美的解决了我的需求。但是怕大佬突然关服了。想在自家nas上搭建此环境，发现大佬的wiki上有docker的部署，请求更新docker，小白一个，实在没能力解决自行搭建，感激不尽。

**Comment by Haoshenqi0123** [comment]
done
[使用容器(docker-compose)运行](https://github.com/Haoshenqi0123/holiday/wiki/%E4%BD%BF%E7%94%A8%E5%AE%B9%E5%99%A8%E8%BF%90%E8%A1%8C)
