### ISSUE TITLE
有没有什么办法获取到工资倍数

### ISSUE THREAD

**Issue by forayl** [Haoshenqi0123/holiday#2]
百度的API没有字段参考文档，如果从GOV获取的话有没有什么好的办法？

**Comment by Haoshenqi0123** [comment]
根据status啊 1周末两倍，3法定节假日3倍。
其他地方要自己写爬虫了

**Comment by Haoshenqi0123** [comment]
> 百度的API没有字段参考文档，如果从GOV获取的话有没有什么好的办法？

根据status啊 1周末两倍，3法定节假日3倍。
其他地方要自己写爬虫了
