### ISSUE TITLE
返回的数据不对

### ISSUE THREAD

**Issue by darling331** [Haoshenqi0123/holiday#5]
您好，按照您的readme的说明，我这边调用了接口，返回的数据不正确，比如当data参数是2021-01-01的时候，返回的数据status=0 正确的数据是应该是元旦节假日。

**Comment by Haoshenqi0123** [comment]
是的，readme写了。百度修改了api。爬虫抓不到数据了。最近工作比较忙，我会尽量在2月份之前写好爬虫。

**Comment by s284309258** [comment]
这个最近能修复下吗，我们都是用这个接口判断提现的，如果接口不对那提现就会有问题了
